version: '3.8'
services:

    server:
      build: .
      ports: 
        - 8080:5000
      links:
        - db

    db:
      image: mysql:5.7.16
      ports:
      - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      